openimis/openimis-fe-insuree_js

- src/actions.js
- src/components/FamilyForm.js
While creating a family, if you click on refresh button after save, you should be redirect to the new family overview.
> OMT-274: fetch family uuid and redirect to overview

- src/actions.js
- src/components/InsureeMasterPanel.js
- src/pickers/InsureeNumberInput.js
- src/reducer.js
https://openimis.atlassian.net/browse/OP-1080
This PR changes the way Insuree No. field is validated. Now it uses generic component ValidatedTextInput to validate.
It is connected with its backend part: https://github.com/openimis/openimis-be-insuree_py/pull/45
> OP-1080: update frontend logic for Insuree number validation

- src/actions.js
- src/components/InsureeForm.js
- src/pickers/InsureeNumberInput.js
- src/reducer.js
- src/translations/en.json
[OTC-811](https://openimis.atlassian.net/browse/OTC-811)
In scope of this ticket, I corrected the validation of the insuree number. Now, when it is invalid, there is no possibility to save the form (save button is disabled).
Moreover, the warning message has been changed from "_Invalid Insuree Number_" to "_Insurance number already in use_".
Related BE: [CORE PR](https://github.com/openimis/openimis-be-core_py/pull/148) and [INSUREE PR](https://github.com/openimis/openimis-be-insuree_py/pull/47)
[OTC-811]: https://openimis.atlassian.net/browse/OTC-811?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> OTC-811: Validation of insuree number fix

- src/components/InsureeMasterPanel.js
- src/pickers/InsureeNumberInput.js
https://openimis.atlassian.net/browse/OTC-915
This PR fixes a situation when insuree number validation would accept a number that was left in state during creation of a new insuree.
> OTC-915: when creating an insuree it will always validate its number

- src/components/FamilySearcher.js
- src/components/InsureeSearcher.js
- src/pickers/InsureePicker.js
[OP-1084](https://openimis.atlassian.net/browse/OP-1084)
Changes:
- Pagination fix in _**FamilySearcher.js**_, _**InsureeSearcher.js**_ and **_InsureePicker.js_**. **Last** and **first** parameters had to be adjusted to the existing logic.
[OP-1084]: https://openimis.atlassian.net/browse/OP-1084?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> OP-1084: FamilySearcher, InsureeSearcher, InsureePicker pagination fix

- src/actions.js
- src/components/FamilyForm.js
- src/components/HeadInsureeMasterPanel.js
- src/components/InsureeForm.js
- src/components/InsureeMasterPanel.js
- src/pages/FamilyPage.js
- src/pickers/InsureeNumberInput.js
- src/pickers/InsureePicker.js
- src/reducer.js
[OTC-989](https://openimis.atlassian.net/browse/OTC-989)
Changes:
- Implementation of additional state which clarifies when user is selecting existing insuree as a head.
- Implementation of _clearInsuree_ action and using it where it is neccessary.
Now, user can select an existing insuree as a head and if all required fields are filled, the form allows to save. Moreover, if there will be a change of insuree number, it is still validated and there is no way to save a form with duplicated code.
[OTC-989]: https://openimis.atlassian.net/browse/OTC-989?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> OTC-989: Selecting existing insuree as a head fix

- src/actions.js
- src/components/FamilyForm.js
- src/components/InsureeForm.js
[OTC-1012](https://openimis.atlassian.net/browse/OTC-1012)
Changes:
1. Fetching insuree mutation to enable redirect to specified paths after reload and to adjust styles/_readOnly_ property.
2. There are 4 scenarios which were considered here:
- reloading after save when an insuree was **created** or **edited** (from the **family overview panel**) --> redirect to **this family** overview panel
- reloading after save when an insuree was **edited** (from the **insurees tab**) --> redirect to **this insuree** and enable editing
- reloading after save when an insuree was **created** (from the **insurees tab**) --> redirect to **this** newly created **insuree** and enable editing
At the moment, if you create an insuree from the insurees tab, the family is not attached to it and it is not …
> OTC-1012: Editing after save blocked, restoring reload functionality

- src/components/FamilyFilter.js
- src/components/FamilyForm.js
- src/components/FamilyInsureesOverview.js
- src/components/InsureeFilter.js
- src/components/InsureeForm.js
- src/components/InsureeMasterPanel.js
[OP-1309](https://openimis.atlassian.net/browse/OP-1309)
Changes:
- The form will not be saved if there are no changes made or if the gender is not specified.
- Removed redundant imports that were causing warnings in the terminal when the module was executed.
[OP-1309]: https://openimis.atlassian.net/browse/OP-1309?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> OP-1309: Prevent saving if no changes or gender is not precised

- src/reducer.js
[OP-1414](https://openimis.atlassian.net/browse/OP-1414)
Changes:
- Family has been added to the insuree reducer. It allows user to see family details when overviewing an insuree.
[OP-1414]: https://openimis.atlassian.net/browse/OP-1414?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> OP-1414: Use insurees family if family is not fetched

- src/components/FamilyFilter.js
- src/components/InsureeFilter.js
[OTC-1089](https://openimis.atlassian.net/browse/OTC-1089)
Changes:
- The functionality for clearing the search criterias when clicking "Reset" button fixed.
- I got rid of the local state and implemented enhanced logic to handle checkbox buttons.
- Implementation of generic function to handle checkbox change.
[OTC-1089]: https://openimis.atlassian.net/browse/OTC-1089?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> OTC-1089: fix resetting the search criteria in insuree module

- src/components/FamilyForm.js
[OP-1530](https://openimis.atlassian.net/browse/OP-1530)
Changes:
- Check if chfId of headInsuree is valid only in if family is not defined.
[OP-1530]: https://openimis.atlassian.net/browse/OP-1530?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> OP-1530: check if chfid valid only if family not defined

- src/components/FamilyForm.js
- src/components/InsureeForm.js
- src/utils/utils.js
[OP-1434](https://openimis.atlassian.net/browse/OP-1434)
Changes:
- Editing historical data is not allowed and saving such data is impossible.
- There is a specific background to indicate that a user is viewing historical data.
[OP-1434]: https://openimis.atlassian.net/browse/OP-1434?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> OP-1434: block editing historical data, indication about historical data

- src/reducer.js
Changes:
- Revert https://github.com/openimis/openimis-fe-insuree_js/pull/63. It was causing issues with creating an insuree from the family overview.
> hotfix: restore insuree creation from family view

- src/actions.js
- src/components/FamilyMembersTable.js
- src/components/InsureeProfileLink.js
- src/components/InsureeSummary.js
- src/constants.js
- src/index.js
- src/pages/ProfilePage.js
- src/reducer.js
- src/translations/en.json
- src/utils/utils.js
[ONI-95](https://openimis.atlassian.net/browse/ONI-95)
[RELATED PR #1](https://github.com/openimis/openimis-fe-policy_js/pull/62)
[RELATED PR #2](https://github.com/openimis/openimis-fe-claim_js/pull/148)
Changes:
- Implementation of Insuree Profile page.
- Displaying basic information about insuree, it's policies and related claims.
[ONI-95]: https://openimis.atlassian.net/browse/ONI-95?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> ONI-95: profile page implementation

- src/components/InsureeProfileLink.js
- src/components/InsureeSummary.js
- src/pages/ProfilePage.js
- src/translations/en.json
[ONI-95](https://openimis.atlassian.net/browse/ONI-95)
Changes:
- Align button styles in Insuree enquire.
- Hide 'Create new policy' button.
[ONI-95]: https://openimis.atlassian.net/browse/ONI-95?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> ONI-95: align button styles

- src/actions.js
[ONI-173](https://openimis.atlassian.net/browse/ONI-173)
Change:
- Fill missing fields in head insuree projection. (Fetching all fields except family - fetching family was causing circular dependency between insuree and family - in this case, we can omit fetching family).
[ONI-173]: https://openimis.atlassian.net/browse/ONI-173?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> ONI-173: change insuree head projection

- src/components/InsureeMasterPanel.js
Ticket: https://openimis.atlassian.net/browse/ONI-169
Changes:
- If insuree is added their status is set as active and cannot be changed
- Removed "any" option from dropdowns.
> ONI-169: Insuree status set for new insurees.

- README.md
- src/constants.js
- src/menus/InsureeMainMenu.js
- src/translations/en.json
[OM-79](https://openimis.atlassian.net/browse/OM-79)
[REQUIRED PR](https://github.com/openimis/openimis-fe-worker_voucher_js/pull/1)
Changes:
- If user is using Moldova setup, instead of _Insurees and Policies_ display _Workers and Vouchers_.
[OM-79]: https://openimis.atlassian.net/browse/OM-79?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> OM-79: add new navbar node on setting

- src/components/InsureeForm.js
- src/components/InsureeMasterPanel.js
[OP-1695](https://openimis.atlassian.net/browse/OP-1695)
Changes:
- Creating an insuree from the family overview page is possible now.
[OP-1695]: https://openimis.atlassian.net/browse/OP-1695?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> OP-1695: fix creating insuree from family panel

- src/components/InsureeForm.js
[OP-1699](https://openimis.atlassian.net/browse/OP-1699)
Changes:
- If insuree does not have family registered, use family fetched on mount.
[OP-1699]: https://openimis.atlassian.net/browse/OP-1699?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> OP-1699: if no family, update insuree and save family

- src/components/InsureeForm.js
[OP-1395](https://openimis.atlassian.net/browse/OP-1395)
Change:
- Reload functionality redirects to the insuree page instead of family page.
[OP-1395]: https://openimis.atlassian.net/browse/OP-1395?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> OP-1395: fix insuree reload

- src/components/FamilyMasterPanel.js
- src/components/InsureeMasterPanel.js
[OP-1725](https://openimis.atlassian.net/browse/OP-1725)
Changes:
- Remove the 'none/null' option from the dropdowns menu in the form.
[OP-1725]: https://openimis.atlassian.net/browse/OP-1725?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> OP-1725: remove null/empty options from dropdowns

- README.md
- src/utils/utils.js
Ticket: https://openimis.atlassian.net/browse/ONI-156
BE check: https://github.com/openimis/openimis-be-insuree_py/pull/114
Changes:
- Added setting for photo to be required
- If required - saving is blocked without photo, but no indication in form - non-standard field.
> ONI-156: Added setting to set photo as required.

- src/components/InsureeSearcher.js
[OM-113](https://openimis.atlassian.net/browse/OM-113)
Changes:
- If _isWorker_ true, do not display a family link button.
[OM-113]: https://openimis.atlassian.net/browse/OM-113?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> OM-113: remove family button is isWorker true

- src/actions.js
- src/components/InsureeSearcher.js
- src/reducer.js
- src/translations/en.json
[OM-118](https://openimis.atlassian.net/browse/OM-118)
[CORE BE PR](https://github.com/openimis/openimis-be-core_py/pull/253)
[INSUREE BE PR](https://github.com/openimis/openimis-be-insuree_py/pull/117)
Changes:
- Add a "Download Workers" button to export all worker search results.
- Lokalise keys have been updated.
[OM-118]: https://openimis.atlassian.net/browse/OM-118?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> OM-118: add workers export functionality

- src/pickers/InsureeChfIdPicker.js
[OP-1748](https://openimis.atlassian.net/browse/OP-1748)
Changes:
- If insuree not found, instead of empty field, display 'Not Found' placeholder.
[OP-1748]: https://openimis.atlassian.net/browse/OP-1748?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> OP-1748: add placeholder notfound

- src/constants.js
- src/menus/InsureeMainMenu.js
[OM-122](https://openimis.atlassian.net/browse/OM-122)
[RELATED PR](https://github.com/openimis/openimis-fe-worker_voucher_js/pull/25)
Changes:
- Make rendering routes configurable based on config, not only on rights.
[OM-122]: https://openimis.atlassian.net/browse/OM-122?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> OM-122: make generic vouchers configurable

- src/components/FamilySearcher.js
- src/components/InsureeSearcher.js
[OP-1817](https://openimis.atlassian.net/browse/OP-1817)
Changes:
- InsureeSearcher | FamilySearcher : Show or hide "Validity From" and "Validity To" columns based on the showHistory filter.
[OP-1817]: https://openimis.atlassian.net/browse/OP-1817?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> OP-1817: hide validity dates if historical data not requested

- src/components/InsureeFilter.js
[OP-1818](https://openimis.atlassian.net/browse/OP-1818)
Changes:
- Fix the _InsureeFilter_ to accurately filter dates, ensuring it does not cause crashes in the secondary calendar functionality.
[OP-1818]: https://openimis.atlassian.net/browse/OP-1818?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> OP-1818: pass min/max date properly

- src/components/InsureeFilter.js
- src/components/InsureeForm.js
- src/components/InsureeSearcher.js
- src/menus/InsureeMainMenu.js
[OM-131](https://openimis.atlassian.net/browse/OM-131)
Changes:
- Change isWorker source from "fe-insuree" to "fe-core" as it is used across multiple modules.
[OM-131]: https://openimis.atlassian.net/browse/OM-131?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> OM-131: change isWorker source
