openimis/openimis-fe-insuree_js

src/actions.js
src/components/FamilyMasterPanel.js

Part of [OTC-289](https://openimis.atlassian.net/browse/OTC-289)

OTC-289: Added contribution point in family panel form

---

src/components/FamilyFilter.js
src/components/FamilySearcher.js
src/pages/FamiliesPage.js

TICKET: [OTC-303](https://openimis.atlassian.net/browse/OTC-303)

OTC-303: Additional filters handling 

---

src/components/InsureeMasterPanel.js
src/pickers/InsureeNumberInput.js

Required changes in backend: [OP-818](https://github.com/openimis/openimis-be-insuree_py/pull/36)
TICKET: [OP-818](https://openimis.atlassian.net/browse/OP-818)

OP-818: Fixed Insuree Number validation

---

src/components/FamilyForm.js
src/components/InsureeSearcher.js

TICKET: [OTC-732](https://openimis.atlassian.net/browse/OTC-732)

OTC-732: Additional check for confirm action

---

src/pickers/InsureeChfIdPicker.js

https://openimis.atlassian.net/browse/OP-992

OP-992: modular IMIS: Insuree No in the claim form is hardly to be entered

---

src/actions.js
src/components/InsureeSearcher.js

https://openimis.atlassian.net/browse/OP-1027

OP-1027: modular IMIS: the front end doesn't support portability of benefits.

---

src/components/HeadInsureeMasterPanel.js

https://openimis.atlassian.net/browse/OP-1079
The title of the pull request says it all.

OP-1079: fix a bug where you couldn't choose a head of a family when insuree was chosen from a list of existing insurees

---

src/components/FamilyFilter.js
src/pages/FamilyPage.js
src/pages/InsureePage.js
src/pickers/InsureeNumberInput.js

TICKET: [OTC-817](https://openimis.atlassian.net/browse/OTC-817)
[OTC-817]: https://openimis.atlassian.net/browse/OTC-817?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

OTC-817: Fixed readOnly in family and insuree

---

src/components/FamilyForm.js
src/components/InsureeForm.js

https://openimis.atlassian.net/browse/OTC-966

OTC-966: make save button always visible

---

src/components/InsureeMasterPanel.js

Ticket:
https://openimis.atlassian.net/browse/OTC-1058
Changes:
- disabled past dates from birth date picker

Feature/otc 1058: disabled past dates from birth date picker

---

src/reducer.js

https://openimis.atlassian.net/browse/OTC-1067

OTC-1067: modularIMIS: when creating an insuree from family panel loading icon appears

---

src/components/InsureeFirstServicePointPanel.js

https://openimis.atlassian.net/browse/OTC-950

OTC-950: District dropdown and HFs under FSP displays only mapped district of the logged in user

---

src/components/InsureeFirstServicePointPanel.js

MERGING RELEASE branches
Release release/23.04

MERGING RELEASE branches

---

src/components/InsureeSearcher.js

Ticket: https://openimis.atlassian.net/browse/ONI-121
Changes:
- Added support for changing date type in the insuree forms.
- Pressing the toggle button will now switch already saved data as well.

ONI-121: Add support for secondary calendar in the insuree form.

---

src/actions.js

https://openimis.atlassian.net/browse/OP-1479
Adding uuid to the payload while fetching insurees

OP-1479: Policy creation error

---

src/components/InsureeSearcher.js

"ONI-121: Add support for secondary calendar display in the insuree fields. (#68)"
This reverts commit 40dac654df0010be9cf5300e1d16a191e4655809.
Ticket: https://openimis.atlassian.net/browse/ONI-125

Revert ONI-121

---

src/pickers/InsureeChfIdPicker.js

https://openimis.atlassian.net/browse/OP-781
This PR changes nulls to "" in text input so the value would reset.
It is related to:
https://github.com/openimis/openimis-fe-claim_js/pull/128

OP-781: fix insuree chf picker

---

README.md

Ticket: https://openimis.atlassian.net/browse/ONI-147
Changes:
- Added missing setting info to readme.

ONI-147: Missing setting description added to Readme.

---

src/components/InsureeAddress.js
src/constants.js

[OP-1531](https://openimis.atlassian.net/browse/OP-1531)
Changes:
- Make 'Same Village as Family' and 'Same Address as Family' always visible.
- Fix all bugs in component (I prescribed the component to the function one).
[OP-1531]: https://openimis.atlassian.net/browse/OP-1531?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

OP-1531: make checkbox always visible

---

src/components/InsureeSummary.js
src/translations/en.json

Ticket: https://openimis.atlassian.net/browse/ONI-14
Changes:
- Added "go to family" button to enquire

ONI-14: Added go to family button to enquire.

---

src/components/FamilyForm.js
src/components/InsureeForm.js
src/utils/utils.js

[OP-1547](https://openimis.atlassian.net/browse/OP-1547)
Changes:
- Create a util function which will unify insuree validation.
[OP-1547]: https://openimis.atlassian.net/browse/OP-1547?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

OP-1547: create util function for insuree validation

---

src/actions.js

[ONI-84](https://openimis.atlassian.net/browse/ONI-84)
[RELATED PR](https://github.com/openimis/openimis-fe-claim_js/pull/143)
Changes:
- Add date of birth to projection.
[ONI-84]: https://openimis.atlassian.net/browse/ONI-84?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

ONI-84: add dob to projection

---

README.md
src/actions.js
src/components/InsureeSummary.js
src/translations/en.json

Ticket: https://openimis.atlassian.net/browse/ONI-16
Changes:
- Added insuree address field in enquire.
- Proper setting added.

ONI-16: Add insuree address in enquire.

---

README.md
src/actions.js
src/components/InsureeSummary.js
src/reducer.js
src/translations/en.json

Changes:
- Revert https://github.com/openimis/openimis-fe-insuree_js/pull/63. It was causing issues with creating an insuree from the family overview.

hotfix: restore insuree creation from family view 

---

README.md
src/actions.js
src/components/InsureeMasterPanel.js
src/constants.js
src/index.js
src/pickers/InsureeStatusDatePicker.js
src/pickers/InsureeStatusPicker.js
src/pickers/InsureeStatusReasonPicker.js
src/translations/en.json
src/utils/utils.js

Ticket: https://openimis.atlassian.net/browse/ONI-3
BE: https://github.com/openimis/openimis-be-insuree_py/pull/74
Changes:
- Added fields for insuree status/date of status/reason of status
- Relevant setting added

ONI-3: Added insuree status dropdown.

---

src/actions.js
src/components/FamilyForm.js
src/components/FamilyMasterPanel.js
src/pickers/ConfirmationTypePicker.js
src/reducer.js

Ticket: https://openimis.atlassian.net/browse/ONI-5
BE: https://github.com/openimis/openimis-be-insuree_py/pull/89
Changes:
- Added check for confirmation number.
- If confirmation type requires number that field becomes required.

ONI-5: Confirmation number required on condition.

---

src/actions.js
src/components/InsureeFilter.js
src/components/InsureeForm.js
src/components/InsureeMasterPanel.js
src/components/InsureeSearcher.js
src/components/worker/WorkerMasterPanel.js
src/constants.js
src/translations/en.json
src/utils/utils.js

https://openimis.atlassian.net/browse/OM-48
This PR allows to to add worker as insuree depending on config.
To make it work the following value should be inserted into the database:
```
INSERT INTO "core_ModuleConfiguration" (id,"module","version",config,is_disabled_until,is_exposed,layer) VALUES
('72e8b596-22d5-42f0-9ec4-4d5b725db9f2','fe-insuree','1.0.0','{
"isWorker" : 1
}',NULL,true,'fe');
```
insureeForm.chfIdMaxLength config should be 13

OM-10: allow to add worker as insuree

---

src/translations/en.json

Ticket: https://openimis.atlassian.net/browse/OP-1685
Changes:
- Removed redundant '' signs.
- Chfid now displayed properly.

OP-1685: display chfid properly.

---

src/components/FamilyMembersTable.js
src/translations/en.json

The Insuree Profile was initially established for insurees with families. With recent changes, minor modifications have been necessary.

hotfix: add info if insuree without family

---

README.md
src/components/FamilyFilter.js
src/components/FamilyInsureesOverview.js
src/components/FamilyMasterPanel.js
src/components/FamilyMembersTable.js
src/components/FamilySearcher.js
src/components/InsureeFilter.js
src/components/InsureeMasterPanel.js
src/components/InsureeSearcher.js
src/components/InsureeSummary.js
src/constants.js
src/pages/ProfilePage.js
src/pickers/InsureeChfIdPicker.js
src/pickers/InsureeOfficerPicker.js
src/pickers/InsureePicker.js

[ONI-164](https://openimis.atlassian.net/browse/ONI-164)
Changes:
- Added the 'renderLastNameFirst' setting to enable the rearrangement of field order.
[ONI-164]: https://openimis.atlassian.net/browse/ONI-164?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

ONI-164: add setting to enable displaying first name before second name

---

src/actions.js
src/components/InsureeSummary.js
src/pages/ProfilePage.js
src/utils/utils.js

[ONI-16](https://openimis.atlassian.net/browse/ONI-16)
Changes:
- Add missing informations about region and address details. Moreover, if family not found, display info about it.
[ONI-16]: https://openimis.atlassian.net/browse/ONI-16?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

ONI-16: add missing region and address details info

---

src/components/EnquiryDialog.js
src/translations/en.json

[OP-1822](https://openimis.atlassian.net/browse/OP-1822)
[REQUIRED](https://github.com/openimis/openimis-fe-policy_js/pull/86)
Changes:
- Disable selection of policy in enquiry dialog.
[OP-1822]: https://openimis.atlassian.net/browse/OP-1822?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

OP-1822: disable selection in enquiry dialog

---

src/components/EnquiryDialog.js

fix: fix typo

---

src/components/InsureeForm.js

[OM-147](https://openimis.atlassian.net/browse/OM-147)
Changes:
- Add dob / gender placeholder if creating workers. It is necessary to make worker compatible with insuree mutations.
[OM-147]: https://openimis.atlassian.net/browse/OM-147?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

OM-147: add placeholder of dob and gender if worker

---

src/components/InsureeForm.js

MERGING develop into release/24.04

MERGING develop into release/24.04

---

src/components/Enquiry.js
src/constants.js

Ticket:
https://openimis.atlassian.net/browse/CQI-161
Changes:
- added FE input limits
BE:
https://github.com/openimis/openimis-be-insuree_py/pull/137
FE can be merged without BE.

CQI-161: enquiry input limiter
